# Generated by Django 4.2.1 on 2023-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='send_bot',
            field=models.BooleanField(default=True, help_text='ボットの時False'),
        ),
    ]
