# Generated by Django 4.2.1 on 2023-05-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_talk_send_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='send_bot',
            field=models.BooleanField(default=True, help_text='ボットの時True'),
        ),
    ]
